In [35]:
import pyarrow as pa
import pyarrow.parquet as pq
import pandas as pd

pq_file = '/home/dcai/data/EURCHF/2019/49.parquet'
table = pq.read_table(pq_file)

# Convert the PyArrow table to a Pandas dataframe
df = table.to_pandas()

#df['mean'] = df.mean(axis=1, numeric_only=True)

# Print the dataframe
print(df[0:20])
print(df.dtypes)

                             Bid      Ask      mean   spread  spread_pip
DateTime
2019-12-01 22:00:03.133  1.10148  1.10250  1.101990  0.00102        10.2
2019-12-01 22:01:03.133  1.10142  1.10250  1.101960  0.00108        10.8
2019-12-01 22:02:03.133  1.10141  1.10250  1.101955  0.00109        10.9
2019-12-01 22:02:15.386  1.10140  1.10253  1.101965  0.00113        11.3
2019-12-01 22:02:15.547  1.10145  1.10250  1.101975  0.00105        10.5
2019-12-01 22:02:47.876  1.10134  1.10256  1.101950  0.00122        12.2
2019-12-01 22:02:48.107  1.10154  1.10250  1.102020  0.00096         9.6
2019-12-01 22:02:48.241  1.10134  1.10256  1.101950  0.00122        12.2
2019-12-01 22:02:48.251  1.10135  1.10257  1.101960  0.00122        12.2
2019-12-01 22:03:23.811  1.10134  1.10256  1.101950  0.00122        12.2
2019-12-01 22:03:32.894  1.10188  1.10256  1.102220  0.00068         6.8
2019-12-01 22:03:41.721  1.10188  1.10255  1.102215  0.00067         6.7
2019-12-01 22:03:42.396  1.10188  1.10213  1.102005  0.00025         2.5
2019-12-01 22:03:52.836  1.10189  1.10213  1.102010  0.00024         2.4
2019-12-01 22:03:57.386  1.10188  1.10213  1.102005  0.00025         2.5
2019-12-01 22:03:58.410  1.10189  1.10213  1.102010  0.00024         2.4
2019-12-01 22:03:58.909  1.10188  1.10213  1.102005  0.00025         2.5
2019-12-01 22:03:58.936  1.10194  1.10219  1.102065  0.00025         2.5
2019-12-01 22:03:59.988  1.10191  1.10216  1.102035  0.00025         2.5
2019-12-01 22:04:00.824  1.10187  1.10212  1.101995  0.00025         2.5
Bid           float64
Ask           float64
mean          float64
spread        float64
spread_pip    float64
dtype: object

In [34]:
df['spread'] = df['Ask']-df['Bid']
df['spread_pip'] = df['spread']*10000.0

df.head(10)

                             Bid      Ask      mean   spread  spread_pip
DateTime
2019-12-01 22:00:03.133  1.10148  1.10250  1.101990  0.00102        10.2
2019-12-01 22:01:03.133  1.10142  1.10250  1.101960  0.00108        10.8
2019-12-01 22:02:03.133  1.10141  1.10250  1.101955  0.00109        10.9
2019-12-01 22:02:15.386  1.10140  1.10253  1.101965  0.00113        11.3
2019-12-01 22:02:15.547  1.10145  1.10250  1.101975  0.00105        10.5
2019-12-01 22:02:47.876  1.10134  1.10256  1.101950  0.00122        12.2
2019-12-01 22:02:48.107  1.10154  1.10250  1.102020  0.00096         9.6
2019-12-01 22:02:48.241  1.10134  1.10256  1.101950  0.00122        12.2
2019-12-01 22:02:48.251  1.10135  1.10257  1.101960  0.00122        12.2
2019-12-01 22:03:23.811  1.10134  1.10256  1.101950  0.00122        12.2

In [36]:
df_small  = df[0:100]
df_small

                             Bid      Ask      mean   spread  spread_pip
DateTime
2019-12-01 22:00:03.133  1.10148  1.10250  1.101990  0.00102        10.2
2019-12-01 22:01:03.133  1.10142  1.10250  1.101960  0.00108        10.8
2019-12-01 22:02:03.133  1.10141  1.10250  1.101955  0.00109        10.9
2019-12-01 22:02:15.386  1.10140  1.10253  1.101965  0.00113        11.3
2019-12-01 22:02:15.547  1.10145  1.10250  1.101975  0.00105        10.5
...                          ...      ...       ...      ...         ...
2019-12-01 22:05:32.497  1.10165  1.10263  1.102140  0.00098         9.8
2019-12-01 22:05:34.070  1.10166  1.10263  1.102145  0.00097         9.7
2019-12-01 22:05:34.115  1.10166  1.10258  1.102120  0.00092         9.2
2019-12-01 22:05:34.122  1.10170  1.10263  1.102165  0.00093         9.3
2019-12-01 22:05:36.006  1.10168  1.10263  1.102155  0.00095         9.5

[100 rows x 5 columns]

In [57]:
import math
from pandas import Series

def log_add(array_like):
    return (10*math.log10((sum([10**(i/10) for i in array_like]))))

def idx_of_non_nan(values):
    return values==values

## https://pandas.pydata.org/docs/reference/api/pandas.core.resample.Resampler.pipe.html

breaks='1min'
ts2 = Series(df_small['mean'].values, index=df_small.index)
ohcl = ts2.resample(breaks).ohlc()
minMax = ts2.resample(breaks).pipe(lambda x: x.min() - x.max())
closeOpen = ts2.resample(breaks).pipe(lambda x: x.last() - x.first())

count = ts2.resample(breaks).count()

mean = ts2.resample(breaks).mean()

median = ts2.resample(breaks).median()

sem = ts2.resample(breaks).sem()

std = ts2.resample(breaks).std()

var = ts2.resample(breaks).var()

q1 = ts2.resample(breaks).quantile(q=0.25)

q3 = ts2.resample(breaks).quantile(q=0.75)

df5 = pd.concat([ohcl, minMax, closeOpen,count, mean, median, sem, std, var, q1, q3], axis=1)

df5.rename(columns={0 : 'MinMax', 1 : 'Move', 2: 'Count', 3: 'Mean', 4: 'Median', 5: 'Sem', 6: 'Std', 7: 'Var', 8: 'Q1', 9: 'Q3'}, inplace=True)

print(df5)

                         open      high       low     close   MinMax  \
DateTime
2019-12-01 22:00:00  1.101990  1.101990  1.101990  1.101990  0.00000
2019-12-01 22:01:00  1.101960  1.101960  1.101960  1.101960  0.00000
2019-12-01 22:02:00  1.101955  1.102020  1.101950  1.101960 -0.00007
2019-12-01 22:03:00  1.101950  1.102220  1.101950  1.102035 -0.00027
2019-12-01 22:04:00  1.101995  1.102375  1.101985  1.102115 -0.00039
2019-12-01 22:05:00  1.102135  1.102715  1.101985  1.102155 -0.00073

                         Move  Count      Mean    Median       Sem       Std  \
DateTime
2019-12-01 22:00:00  0.000000      1  1.101990  1.101990       NaN       NaN
2019-12-01 22:01:00  0.000000      1  1.101960  1.101960       NaN       NaN
2019-12-01 22:02:00  0.000005      7  1.101968  1.101960  0.000009  0.000025
2019-12-01 22:03:00  0.000085     10  1.102052  1.102010  0.000029  0.000092
2019-12-01 22:04:00  0.000120     24  1.102081  1.102045  0.000020  0.000096
2019-12-01 22:05:00  0.000020     57  1.102291  1.102170  0.000030  0.000228

                              Var        Q1        Q3
DateTime
2019-12-01 22:00:00           NaN  1.101990  1.101990
2019-12-01 22:01:00           NaN  1.101960  1.101960
2019-12-01 22:02:00  6.071429e-10  1.101952  1.101970
2019-12-01 22:03:00  8.423333e-09  1.102005  1.102057
2019-12-01 22:04:00  9.158650e-09  1.102015  1.102127
2019-12-01 22:05:00  5.186142e-08  1.102145  1.102565

In [75]:
import os

def process_df(df, breaks):
    ts2 = Series(df['mean'].values, index=df.index)
    ohcl = ts2.resample(breaks).ohlc()
    minMax = ts2.resample(breaks).pipe(lambda x: x.min() - x.max())
    closeOpen = ts2.resample(breaks).pipe(lambda x: x.last() - x.first())

    count = ts2.resample(breaks).count()

    mean = ts2.resample(breaks).mean()

    median = ts2.resample(breaks).median()

    sem = ts2.resample(breaks).sem()

    std = ts2.resample(breaks).std()

    var = ts2.resample(breaks).var()

    q1 = ts2.resample(breaks).quantile(q=0.25)

    q3 = ts2.resample(breaks).quantile(q=0.75)

    result = pd.concat([ohcl, minMax, closeOpen,count, mean, median, sem, std, var, q1, q3], axis=1)

    result.rename(columns={0 : 'MinMax', 1 : 'Move', 2: 'Count', 3: 'Mean', 4: 'Median', 5: 'Sem', 6: 'Std', 7: 'Var', 8: 'Q1', 9: 'Q3'}, inplace=True)
    
    return result


def process_raw_many(root_dir, output_dir, breaks):
    for br in breaks:
        process_raw(root_dir, output_dir, br)
        
def mk_missing_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)
        
def extract_instrument_and_year(path):
    tokens = path.split('/')
    return tokens[-2], tokens[-1]

def process_raw(root_dir, output_dir, br):
    filenames = []
    for root, dirs, files in os.walk(root_dir):
        for file in files:
            # Check if the file is a CSV file
            if file.endswith('.parquet'):
                
                
                instrument, year = extract_instrument_and_year(root)
                parquet_file_result = os.path.join(output_dir, instrument, year, "{0}-{1}".format(br,file))
                
                mk_missing_dir(os.path.dirname(parquet_file_result))
                
                parquet_file = os.path.join(root, file)
                table = pq.read_table(parquet_file)
                # Convert the PyArrow table to a Pandas dataframe
                df = table.to_pandas()

                df = process_df(df, br)
                pq.write_table(pa.Table.from_pandas(df), parquet_file_result)
                print(f'Done {parquet_file_result}')

In [76]:
import datetime, itertools, os, glob, shutil
from io import BytesIO
import gzip
import urllib.request
import pathlib
import os
import pyarrow as pa
import pyarrow.parquet as pq
import pandas as pd
import time


breaks=['1Min', '5Min', '10Min', '15Min', '30Min', '1H', '2H', '4H', '6H', '12H', '1D']

start_time = time.time()
process_raw_many('/home/dcai/data/EURCHF', '/home/dcai/data/candles', breaks)
process_raw_many('/home/dcai/data/EURUSD', '/home/dcai/data/candles', breaks)
process_raw_many('/home/dcai/data/GBPCHF', '/home/dcai/data/candles', breaks)
process_raw_many('/home/dcai/data/GBPUSD', '/home/dcai/data/candles', breaks)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'Execution time: {elapsed_time:.3f} seconds')

Done /home/dcai/data/candles/EURCHF/2019/1Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/1Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/1Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-6.parquet

Done /home/dcai/data/candles/EURCHF/2021/1Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/1Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/1Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/1Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-53.parquet

Done /home/dcai/data/candles/EURCHF/2019/5Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/5Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/5Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/5Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-43.parquet

Done /home/dcai/data/candles/EURCHF/2022/5Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/5Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/5Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/10Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-17.parquet

Done /home/dcai/data/candles/EURCHF/2020/10Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/10Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/10Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-29.parquet

Done /home/dcai/data/candles/EURCHF/2022/10Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/10Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/10Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/15Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-53.parquet

Done /home/dcai/data/candles/EURCHF/2020/15Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/15Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/15Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/15Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-25.parquet

Done /home/dcai/data/candles/EURCHF/2018/15Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/15Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/30Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/30Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-33.parquet

Done /home/dcai/data/candles/EURCHF/2021/30Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/30Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/30Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-51.parquet

Done /home/dcai/data/candles/EURCHF/2018/30Min-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/30Min-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/1H-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/1H-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-35.parquet

Done /home/dcai/data/candles/EURCHF/2021/1H-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/1H-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/1H-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/1H-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-53.parquet

Done /home/dcai/data/candles/EURCHF/2019/2H-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/2H-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/2H-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/2H-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-2.parquet

Done /home/dcai/data/candles/EURCHF/2022/2H-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/2H-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/2H-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/4H-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-43.parquet

Done /home/dcai/data/candles/EURCHF/2020/4H-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/4H-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/4H-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/4H-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-45.parquet

Done /home/dcai/data/candles/EURCHF/2018/4H-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/4H-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/6H-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/6H-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-17.parquet

Done /home/dcai/data/candles/EURCHF/2021/6H-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/6H-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/6H-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/6H-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-49.parquet

Done /home/dcai/data/candles/EURCHF/2019/12H-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-8.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/12H-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/12H-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-39.parquet

Done /home/dcai/data/candles/EURCHF/2021/12H-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/12H-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-38.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/12H-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/12H-15.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-49.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-33.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-10.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-41.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-22.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-17.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-5.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-31.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-7.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-46.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-50.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-27.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-45.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-18.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-26.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-13.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-25.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-43.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-42.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-24.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-14.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-36.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-44.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-2.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-4.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-23.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-34.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-19.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-38.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-53.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-20.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-40.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-28.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-47.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-35.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-8.parquet

Done /home/dcai/data/candles/EURCHF/2019/1D-21.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-3.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-32.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-11.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-6.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-51.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-16.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-39.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-29.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-48.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-12.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-9.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-1.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-52.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-37.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-30.parquet
Done /home/dcai/data/candles/EURCHF/2019/1D-15.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-49.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-33.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-10.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-41.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-22.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-17.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-5.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-31.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-7.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-46.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-50.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-27.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-45.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-18.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-26.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-13.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-25.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-43.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-42.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-24.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-14.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-36.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-44.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-2.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-4.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-23.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-34.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-19.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-38.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-53.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-20.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-40.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-28.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-47.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-35.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-8.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-21.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-3.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-32.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-11.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-6.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-51.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-16.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-39.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-29.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-48.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-12.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-9.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-52.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-37.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-30.parquet
Done /home/dcai/data/candles/EURCHF/2020/1D-15.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-49.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-33.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-10.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-41.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-22.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-17.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-5.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-31.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-7.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-46.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-50.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-27.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-45.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-18.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-26.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-13.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-25.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-43.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-42.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-24.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-14.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-36.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-44.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-2.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-4.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-23.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-34.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-19.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-38.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-20.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-40.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-28.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-47.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-35.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-8.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-21.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-3.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-32.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-11.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-6.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-51.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-16.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-39.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-29.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-48.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-12.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-9.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-1.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-52.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-37.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-30.parquet
Done /home/dcai/data/candles/EURCHF/2021/1D-15.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-49.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-33.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-10.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-41.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-22.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-17.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-5.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-31.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-7.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-46.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-50.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-27.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-45.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-18.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-26.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-13.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-25.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-43.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-42.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-24.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-14.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-36.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-44.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-2.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-4.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-23.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-34.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-19.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-38.parquet

Done /home/dcai/data/candles/EURCHF/2022/1D-20.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-40.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-28.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-47.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-35.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-8.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-21.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-3.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-32.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-11.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-6.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-51.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-16.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-39.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-29.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-48.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-12.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-9.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-1.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-37.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-30.parquet
Done /home/dcai/data/candles/EURCHF/2022/1D-15.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-49.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-33.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-10.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-41.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-22.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-17.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-5.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-31.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-7.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-46.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-50.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-27.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-45.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-18.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-26.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-13.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-25.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-43.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-42.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-24.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-14.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-36.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-44.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-2.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-4.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-23.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-34.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-19.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-38.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-20.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-40.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-28.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-47.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-35.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-8.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-21.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-3.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-32.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-11.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-6.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-51.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-16.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-39.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-29.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-48.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-12.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-9.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-1.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-52.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-37.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-30.parquet
Done /home/dcai/data/candles/EURCHF/2018/1D-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/1Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-24.parquet

Done /home/dcai/data/candles/EURUSD/2020/1Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/1Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/1Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/1Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-46.parquet

Done /home/dcai/data/candles/EURUSD/2018/1Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/1Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/5Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-37.parquet

Done /home/dcai/data/candles/EURUSD/2020/5Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/5Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/5Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/5Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-6.parquet

Done /home/dcai/data/candles/EURUSD/2018/5Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/5Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/10Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/10Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-4.parquet

Done /home/dcai/data/candles/EURUSD/2021/10Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/10Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/10Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/10Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-27.parquet

Done /home/dcai/data/candles/EURUSD/2019/15Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/15Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/15Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-52.parquet

Done /home/dcai/data/candles/EURUSD/2021/15Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/15Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/15Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/15Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-8.parquet

Done /home/dcai/data/candles/EURUSD/2019/30Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/30Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/30Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/30Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-14.parquet

Done /home/dcai/data/candles/EURUSD/2022/30Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/30Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/30Min-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/1H-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-46.parquet

Done /home/dcai/data/candles/EURUSD/2020/1H-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/1H-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/1H-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/1H-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-22.parquet

Done /home/dcai/data/candles/EURUSD/2018/1H-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/1H-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/2H-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-37.parquet

Done /home/dcai/data/candles/EURUSD/2020/2H-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/2H-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/2H-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/2H-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-48.parquet

Done /home/dcai/data/candles/EURUSD/2018/2H-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/2H-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/4H-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/4H-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-32.parquet

Done /home/dcai/data/candles/EURUSD/2021/4H-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/4H-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/4H-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/4H-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-28.parquet

Done /home/dcai/data/candles/EURUSD/2019/6H-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/6H-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/6H-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/6H-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-23.parquet

Done /home/dcai/data/candles/EURUSD/2022/6H-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/6H-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/6H-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/12H-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-42.parquet

Done /home/dcai/data/candles/EURUSD/2020/12H-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/12H-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-10.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/12H-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/12H-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-50.parquet

Done /home/dcai/data/candles/EURUSD/2018/12H-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-37.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/12H-15.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-49.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-33.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-10.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-41.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-22.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-17.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-5.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-31.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-7.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-46.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-50.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-27.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-45.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-18.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-26.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-13.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-25.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-43.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-42.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-24.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-14.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-36.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-44.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-2.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-4.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-23.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-34.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-19.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-38.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-53.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-20.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-40.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-28.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-47.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-35.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-8.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-21.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-3.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-32.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-11.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-6.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-51.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-16.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-39.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-29.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-48.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-12.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-9.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-1.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-52.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-37.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-30.parquet
Done /home/dcai/data/candles/EURUSD/2019/1D-15.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-49.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-33.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-10.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-41.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-22.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-17.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-5.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-31.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-7.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-46.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-50.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-27.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-45.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-18.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-26.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-13.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-25.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-43.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-42.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-24.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-14.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-36.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-44.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-2.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-4.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-23.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-34.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-19.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-38.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-53.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-20.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-40.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-28.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-47.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-35.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-8.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-21.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-3.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-32.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-11.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-6.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-51.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-16.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-39.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-29.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-48.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-12.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-9.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-52.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-37.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-30.parquet
Done /home/dcai/data/candles/EURUSD/2020/1D-15.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-49.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-33.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-10.parquet

Done /home/dcai/data/candles/EURUSD/2021/1D-41.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-22.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-17.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-5.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-31.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-7.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-46.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-50.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-27.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-45.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-18.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-26.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-13.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-25.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-43.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-42.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-24.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-14.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-36.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-44.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-2.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-4.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-23.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-34.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-19.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-38.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-20.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-40.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-28.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-47.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-35.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-8.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-21.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-3.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-32.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-11.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-6.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-51.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-16.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-39.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-29.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-48.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-12.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-9.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-1.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-52.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-37.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-30.parquet
Done /home/dcai/data/candles/EURUSD/2021/1D-15.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-49.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-33.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-10.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-41.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-22.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-17.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-5.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-31.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-7.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-46.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-50.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-27.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-45.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-18.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-26.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-13.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-25.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-43.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-42.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-24.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-14.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-36.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-44.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-2.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-4.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-23.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-34.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-19.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-38.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-20.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-40.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-28.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-47.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-35.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-8.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-21.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-3.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-32.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-11.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-6.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-51.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-16.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-39.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-29.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-48.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-12.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-9.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-1.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-37.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-30.parquet
Done /home/dcai/data/candles/EURUSD/2022/1D-15.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-49.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-33.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-10.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-41.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-22.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-17.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-5.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-31.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-7.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-46.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-50.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-27.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-45.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-18.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-26.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-13.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-25.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-43.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-42.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-24.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-14.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-36.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-44.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-2.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-4.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-23.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-34.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-19.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-38.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-20.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-40.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-28.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-47.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-35.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-8.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-21.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-3.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-32.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-11.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-6.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-51.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-16.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-39.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-29.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-48.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-12.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-9.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-1.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-52.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-37.parquet

Done /home/dcai/data/candles/EURUSD/2018/1D-30.parquet
Done /home/dcai/data/candles/EURUSD/2018/1D-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-32.parquet

Done /home/dcai/data/candles/GBPCHF/2021/1Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-19.parquet

Done /home/dcai/data/candles/GBPCHF/2019/5Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/5Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/5Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/5Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-13.parquet

Done /home/dcai/data/candles/GBPCHF/2022/5Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/5Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/5Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/10Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-41.parquet

Done /home/dcai/data/candles/GBPCHF/2020/10Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/10Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/10Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-16.parquet

Done /home/dcai/data/candles/GBPCHF/2022/10Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/10Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/10Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/15Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-19.parquet

Done /home/dcai/data/candles/GBPCHF/2020/15Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/15Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/15Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/15Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-26.parquet

Done /home/dcai/data/candles/GBPCHF/2018/15Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/15Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/30Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/30Min-15.parquet

Done /home/dcai/data/candles/GBPCHF/2021/30Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/30Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/30Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-11.parquet

Done /home/dcai/data/candles/GBPCHF/2018/30Min-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/30Min-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-40.parquet

Done /home/dcai/data/candles/GBPCHF/2021/1H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-23.parquet

Done /home/dcai/data/candles/GBPCHF/2019/2H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/2H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/2H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/2H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-42.parquet

Done /home/dcai/data/candles/GBPCHF/2022/2H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/2H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/2H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/4H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-45.parquet

Done /home/dcai/data/candles/GBPCHF/2020/4H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/4H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/4H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/4H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-31.parquet

Done /home/dcai/data/candles/GBPCHF/2018/4H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/4H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/6H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/6H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-49.parquet

Done /home/dcai/data/candles/GBPCHF/2021/6H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/6H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/6H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-1.parquet

Done /home/dcai/data/candles/GBPCHF/2018/6H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/6H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/12H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/12H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-32.parquet

Done /home/dcai/data/candles/GBPCHF/2021/12H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/12H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/12H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/12H-15.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-49.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-33.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-10.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-41.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-22.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-17.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-5.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-31.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-7.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-46.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-50.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-27.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-45.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-18.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-26.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-13.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-25.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-43.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-42.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-24.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-14.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-36.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-44.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-2.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-4.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-23.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-34.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-19.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-38.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-53.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-20.parquet

Done /home/dcai/data/candles/GBPCHF/2019/1D-40.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-28.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-47.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-35.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-8.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-21.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-3.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-32.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-11.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-6.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-51.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-16.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-39.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-29.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-48.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-12.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-9.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-1.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-52.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-37.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-30.parquet
Done /home/dcai/data/candles/GBPCHF/2019/1D-15.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-49.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-33.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-10.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-41.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-22.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-17.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-5.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-31.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-7.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-46.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-50.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-27.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-45.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-18.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-26.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-13.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-25.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-43.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-42.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-24.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-14.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-36.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-44.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-2.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-4.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-23.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-34.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-19.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-38.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-53.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-20.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-40.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-28.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-47.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-35.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-8.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-21.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-3.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-32.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-11.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-6.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-51.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-16.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-39.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-29.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-48.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-12.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-9.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-52.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-37.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-30.parquet
Done /home/dcai/data/candles/GBPCHF/2020/1D-15.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-49.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-33.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-10.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-41.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-22.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-17.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-5.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-31.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-7.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-46.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-50.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-27.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-45.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-18.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-26.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-13.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-25.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-43.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-42.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-24.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-14.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-36.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-44.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-2.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-4.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-23.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-34.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-19.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-38.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-20.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-40.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-28.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-47.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-35.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-8.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-21.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-3.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-32.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-11.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-6.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-51.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-16.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-39.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-29.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-48.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-12.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-9.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-1.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-52.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-37.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-30.parquet
Done /home/dcai/data/candles/GBPCHF/2021/1D-15.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-49.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-33.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-10.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-41.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-22.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-17.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-5.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-31.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-7.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-46.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-50.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-27.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-45.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-18.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-26.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-13.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-25.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-43.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-42.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-24.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-14.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-36.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-44.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-2.parquet

Done /home/dcai/data/candles/GBPCHF/2022/1D-4.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-23.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-34.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-19.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-38.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-20.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-40.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-28.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-47.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-35.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-8.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-21.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-3.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-32.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-11.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-6.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-51.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-16.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-39.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-29.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-48.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-12.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-9.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-1.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-37.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-30.parquet
Done /home/dcai/data/candles/GBPCHF/2022/1D-15.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-49.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-33.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-10.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-41.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-22.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-17.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-5.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-31.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-7.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-46.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-50.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-27.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-45.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-18.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-26.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-13.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-25.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-43.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-42.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-24.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-14.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-36.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-44.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-2.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-4.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-23.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-34.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-19.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-38.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-20.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-40.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-28.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-47.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-35.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-8.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-21.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-3.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-32.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-11.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-6.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-51.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-16.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-39.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-29.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-48.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-12.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-9.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-1.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-52.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-37.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-30.parquet
Done /home/dcai/data/candles/GBPCHF/2018/1D-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-26.parquet

Done /home/dcai/data/candles/GBPUSD/2020/1Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-22.parquet

Done /home/dcai/data/candles/GBPUSD/2018/1Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/5Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-29.parquet

Done /home/dcai/data/candles/GBPUSD/2020/5Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/5Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/5Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/5Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-8.parquet

Done /home/dcai/data/candles/GBPUSD/2018/5Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/5Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/10Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/10Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-24.parquet

Done /home/dcai/data/candles/GBPUSD/2021/10Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/10Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/10Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/10Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-5.parquet

Done /home/dcai/data/candles/GBPUSD/2019/15Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/15Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/15Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-29.parquet

Done /home/dcai/data/candles/GBPUSD/2021/15Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/15Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/15Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/15Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-20.parquet

Done /home/dcai/data/candles/GBPUSD/2019/30Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/30Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/30Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/30Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-13.parquet

Done /home/dcai/data/candles/GBPUSD/2022/30Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/30Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/30Min-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-22.parquet

Done /home/dcai/data/candles/GBPUSD/2020/1H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1H-15.parquet

Done /home/dcai/data/candles/GBPUSD/2018/1H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/2H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-29.parquet

Done /home/dcai/data/candles/GBPUSD/2020/2H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/2H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/2H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/2H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-6.parquet

Done /home/dcai/data/candles/GBPUSD/2018/2H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/2H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/4H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/4H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-35.parquet

Done /home/dcai/data/candles/GBPUSD/2021/4H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/4H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/4H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/4H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-38.parquet

Done /home/dcai/data/candles/GBPUSD/2019/6H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/6H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/6H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/6H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-36.parquet

Done /home/dcai/data/candles/GBPUSD/2022/6H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/6H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/6H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/12H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-26.parquet

Done /home/dcai/data/candles/GBPUSD/2020/12H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2020/12H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/12H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/12H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-5.parquet

Done /home/dcai/data/candles/GBPUSD/2018/12H-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-12.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/12H-15.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-49.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-33.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-10.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-41.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-22.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-17.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-5.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-31.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-7.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-46.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-50.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-27.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-45.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-18.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-26.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-13.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-25.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-43.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-42.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-24.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-14.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-36.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-44.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-2.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-4.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-23.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-34.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-19.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-38.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-53.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-20.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-40.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-28.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-47.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-35.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-8.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-21.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-3.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-32.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-11.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-6.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-51.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-16.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-39.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-29.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-48.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-12.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-9.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-1.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-52.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-37.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-30.parquet
Done /home/dcai/data/candles/GBPUSD/2019/1D-15.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-49.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-33.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-10.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-41.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-22.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-17.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-5.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-31.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-7.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-46.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-50.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-27.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-45.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-18.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-26.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-13.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-25.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-43.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-42.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-24.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-14.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-36.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-44.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-2.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-4.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-23.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-34.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-19.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-38.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-53.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-20.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-40.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-28.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-47.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-35.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-8.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-21.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-3.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-32.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-11.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-6.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-51.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-16.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-39.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-29.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-48.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-12.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-9.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-52.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-37.parquet
Done /home/dcai/data/candles/GBPUSD/2020/1D-30.parquet

Done /home/dcai/data/candles/GBPUSD/2020/1D-15.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-49.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-33.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-10.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-41.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-22.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-17.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-5.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-31.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-7.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-46.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-50.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-27.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-45.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-18.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-26.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-13.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-25.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-43.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-42.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-24.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-14.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-36.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-44.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-2.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-4.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-23.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-34.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-19.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-38.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-20.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-40.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-28.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-47.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-35.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-8.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-21.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-3.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-32.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-11.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-6.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-51.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-16.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-39.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-29.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-48.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-12.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-9.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-1.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-52.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-37.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-30.parquet
Done /home/dcai/data/candles/GBPUSD/2021/1D-15.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-49.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-33.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-10.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-41.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-22.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-17.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-5.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-31.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-7.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-46.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-50.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-27.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-45.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-18.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-26.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-13.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-25.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-43.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-42.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-24.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-14.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-36.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-44.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-2.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-4.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-23.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-34.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-19.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-38.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-20.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-40.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-28.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-47.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-35.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-8.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-21.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-3.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-32.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-11.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-6.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-51.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-16.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-39.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-29.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-48.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-12.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-9.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-1.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-37.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-30.parquet
Done /home/dcai/data/candles/GBPUSD/2022/1D-15.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-49.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-33.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-10.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-41.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-22.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-17.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-5.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-31.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-7.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-46.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-50.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-27.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-45.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-18.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-26.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-13.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-25.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-43.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-42.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-24.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-14.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-36.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-44.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-2.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-4.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-23.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-34.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-19.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-38.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-20.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-40.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-28.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-47.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-35.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-8.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-21.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-3.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-32.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-11.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-6.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-51.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-16.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-39.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-29.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-48.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-12.parquet

Done /home/dcai/data/candles/GBPUSD/2018/1D-9.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-1.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-52.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-37.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-30.parquet
Done /home/dcai/data/candles/GBPUSD/2018/1D-15.parquet
Execution time: 5880.553 seconds

In [70]:
path = '/a/aa/a/a/a/data/EURCHF/2020'

tokens = path.split('/')
tokens[-2]

'EURCHF'